// <auto-generated />
namespace QuanLySieuthimini1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_table5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_table5));
        
        string IMigrationMetadata.Id
        {
            get { return "202012080651570_add_table5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
